### ISSUE TITLE
dependency removed from CRAN

### ISSUE THREAD

**Issue by albamasmalavila** [VHIOinformatics/BasicPlots#1]
BasicPlots depends on "colorfulVennPlot" package, which was removed from CRAN repository (https://cran.ncc.metu.edu.tr/web/packages/colorfulVennPlot/index.html). 
Consider updating functions using other packages.

**Comment by ireneab97** [comment]
This issue has been solved! colorfulVennPlot is no longer a dependency of the package. Venn plots are now made with ggvenn
